name: tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Sending Mail on Success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.DEVOPS_EMAIL }}
        password: ${{ secrets.DEVOPS_PASSWORD }}
        subject: "Congratulations! Your work is 10/10"
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: ${{ github.event.pull_request.user.login }}
        from: ${{ secrets.DEVOPS_EMAIL }}

    
    - name: Sending Mail on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.DEVOPS_EMAIL }}
        password: ${{ secrets.DEVOPS_EMAIL_PASSWORD }}
        subject: "Sorry! Your work is not up to the mark"
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: ${{ github.event.pull_request.user.login }}
        from: ${{ secrets.DEVOPS_EMAIL }}

